name: java with maven

on:
  push:
    branches: [master]
    pull_request: 
    branches: [master]
    
 jobs:
   Build:
   
     runs-on: ubuntu-latest 
     
    steps:
    ######## Checkout code ########
      - name: 'Checkout repository on branch: ${{ github.REF }}'
        uses: actions/checkout@v2
        continue-on-error: ${{ env.CONTINUE_ON_ERROR }}
        with:
          ref: ${{ github.REF }}
          fetch-depth: 0
          ######## Build - Maven ########
      - name: Build with Maven
        id: build_maven
        if: ${{ env.BUILD_TECH == 'java_maven' }}
        run: |
            mvn ${{ env.MVN_ARGS }}
        continue-on-error: ${{ env.CONTINUE_ON_ERROR }}
